url: https://jetong.me
baseurl: 

# Site settings
title: Jet Ong
email: s10184291@connect.np.edu.sg
description: "Jet Ong's portfolio"

exclude:
  - .jekyll-cache

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

# Google Analytics
google_analytics: UA-150899950-1

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: whatsapp
    url: https://wa.me/6583111007
  - title: skype
    url: skype:jetong01?userinfo
  - title: linkedin
    url: https://linkedin.com/in/jet-ong
  - title: github
    url: http://github.com/j370
  - title: bitbucket 
    url: https://bitbucket.org/%7Ba33d1089-188a-431d-9530-3df8cb71e7a4%7D/
  - title: stack-overflow
    url: https://stackoverflow.com/users/6747179/j370
  

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

skills:
  - name: Java
    fa: true
    logo: java

  - name: Swift
    fa: true
    logo: swift

  - name: Python
    fa: true
    logo: python

  - name: C++
    fa: false
    logo: cplusplus

  - name: C#
    fa: false
    logo: csharp

  - name: Ruby
    fa: false
    logo: ruby

  - name: HTML
    fa: true
    logo: html5

  - name: CSS
    fa: true
    logo: css3

  - name: JavaScript
    fa: true
    logo: javascript

# Awards
awards:
  - year: 2019
    title: break

  - year: Sep 2019
    title: Championship Award WRO Open 1st
    issuer: Science Center Singapore
    inverse: true

  - year: 2018
    title: break

  - year: Aug 2018
    title: Best Presentation Award WRO Open 3rd
    issuer: Science Center Singapore
    inverse: false

  - year: Aug 2018
    title: Championship Award WRO Open 1st
    issuer: Science Center Singapore
    inverse: true

  - year: 2017
    title: break

  - year: Apr 2017
    title: National Youth Achievement Award Singapore (BRONZE)
    issuer: National Youth Achievement Award Council
    inverse: false

  - year: Mar 2017
    title: IDE Challenge Design Award
    issuer:  NullSpace
    inverse: true

  - year: Feb 2017
    title: ITE College East Robotics Challenge Obstacle Category Merit
    issuer: ITE College East
    inverse: false

  - year: 2016
    title: break

  - year: Jun 2016
    title: National RoboPreneur Carnival Champion
    issuer: Admiralty Secondary School/Nanyang Polytechnic
    inverse: true

  - year: Jul 2016
    title: National RoboPreneur Carnival Best Robot Performance 3rd
    issuer: Admiralty Secondary School/Nanyang Polytechnic
    inverse: false

  - year: Jun 2016
    title: National RoboPreneur Carnival Best Research Journal 1st
    issuer: Admiralty Secondary School/Nanyang Polytechnic
    inverse: true

  - year: 2016
    title: Young Engineer Award (GOLD)
    issuer: Singapore Polytechnic
    inverse: false

  - year: 2015
    title: break

  - year: 2015
    title: ITE College East Robotics Challenge Obstacle Category Merit
    issuer: ITE College East
    inverse: true

  - year: 2014
    title: break

  - year: Sep 2014
    title: National Junior Robotics Competition The Entrepreneur Award 3rd
    issuer: Science Centre
    inverse: false

  - year: 2014
    title: Edusave Good Progress Award 2014
    issuer: Ministry of Education Singapore
    inverse: true

  - year: 2014
    title: Students That Achieve - Recognition (STAR) Awards 2014
    issuer:  Chua Chu Kang Secondary School
    inverse: false


# Portfolio
portfolio:
  - modal-id: 7
    title: Unbiased
    subtitle: Portfolio 2 Assignment
    layout: default
    img: unbiased
    project-date: 2019
    tools:  HTML, ASP.NET, Firebase, Python, Artificial Inteligence
    category: Web Application
    description: 7.8/10 bad game reviews are what unbiased is here to fix.
    url: categories#Portfolio-2

  - modal-id: 6
    title: ECycle
    subtitle: Mobile Application Development 1 Assignment
    layout: default
    img: EcycleLogo
    project-date: 2019
    tools:  Android Studio, Java
    category: Android Application
    description: The amount of ewaste we waste a year amounts to the entire great wall of China!
    url: categories#Mobile-Application-Development-1

  - modal-id: 5
    title: Guardian 3.0
    subtitle: World Robot Olympiad(WRO) 2019
    layout: default
    img: smartcities
    project-date: 2019
    tools:  HTML, ASP.NET, Firebase, Python, Artificial Inteligence, Lego Mindstorms, Tetrix, Raspberry Pi
    category: Robotics
    description: Smart Cities - Guardian 3.0 in Hungary
    url: world robot olympiad (wro)/2019/12/02/wro2019.html

  - modal-id: 4
    title: Service Learning to CDAC @ Redhill and Chong Pang Community Club
    subtitle: Fundamentals for IT Professionals 2 Assignment
    layout: default
    img: Service
    project-date: 2019
    tools: Email, Cashless Payment, Social Media
    category: Service Learning
    description: As part of portfolio 2, we went to various Community Clubs to teach various technologies.
    url: fundamentals for it professionals 2/declassified/2019/07/11/fp2a1.html

  - modal-id: 3
    title: Industry Engagement Talks at Google and Alibaba
    subtitle: Fundamentals for IT Professionals 2 Assignment
    layout: default
    img: Google
    project-date: August 2018
    tools: Tensorflow, Alibaba Cloud
    category: Service Learning
    description: Learning AI from Google and startup skills from Alibaba.
    url: fundamentals for it professionals 2/declassified/2019/07/18/fp2a2.html

  - modal-id: 2
    title: Guardian 2.0
    subtitle: World Robot Olympiad(WRO) 2018
    layout: default
    img: foodmatters
    project-date: August 2018
    tools: HTML, ASP.NET, Firebase, Python, Artificial Inteligence, Lego Mindstorms, Raspberry Pi
    category: Robotics
    description: Food matters - Guardian 2.0 in Thailand
    url: world robot olympiad (wro)/2018/10/05/wro2018.html

  - modal-id: 1
    title: Extreme Control
    subtitle: Portfolio 1 Assignment
    layout: default
    img: ExtremeControl
    project-date: 2018
    tools: Android Studio, Java
    category: Android Application
    description: Ever thought that you spend too much time on your mobile devices?
    url: categories#Portfolio-1