url: https://j370.github.io
baseurl: 

# Site settings
title: Jet Ong
email: s10184291@connect.np.edu.sg
description: "Jet Ong's portfolio"
url: j370.github.io

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Google Analytics
google_analytics: UA-150899950-1

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://linkedin.com/in/jet-ong
  - title: github
    url: http://github.com/j370
  - title: bitbucket 
    url: https://bitbucket.org/%7Ba33d1089-188a-431d-9530-3df8cb71e7a4%7D/
  - title: stack-overflow
    url: https://stackoverflow.com/users/6747179/j370
  

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

# Awards
awards:
  - year: 2019
    title: break

  - year: Sep 2019
    title: Championship Award WRO Open 1st
    issuer: Science Center Singapore
    inverse: true

  - year: 2018
    title: break

  - year: Aug 2018
    title: Best Presentation Award WRO Open 3rd
    issuer: Science Center Singapore
    inverse: false

  - year: Aug 2018
    title: Championship Award WRO Open 1st
    issuer: Science Center Singapore
    inverse: true

  - year: 2017
    title: break

  - year: Apr 2017
    title: National Youth Achievement Award Singapore (BRONZE)
    issuer: National Youth Achievement Award Council
    inverse: false

  - year: Mar 2017
    title: IDE Challenge Design Award
    issuer:  NullSpace
    inverse: true

  - year: Feb 2017
    title: ITE College East Robotics Challenge Obstacle Category Merit
    issuer: ITE College East
    inverse: false

  - year: 2016
    title: break

  - year: Jun 2016
    title: National RoboPreneur Carnival Champion
    issuer: Admiralty Secondary School/Nanyang Polytechnic
    inverse: true

  - year: Jul 2016
    title: National RoboPreneur Carnival Best Robot Performance 3rd
    issuer: Admiralty Secondary School/Nanyang Polytechnic
    inverse: false

  - year: Jun 2016
    title: National RoboPreneur Carnival Best Research Journal 1st
    issuer: Admiralty Secondary School/Nanyang Polytechnic
    inverse: true

  - year: 2016
    title: Young Engineer Award (GOLD)
    issuer: Singapore Polytechnic
    inverse: false

  - year: 2015
    title: break

  - year: 2015
    title: ITE College East Robotics Challenge Obstacle Category Merit
    issuer: ITE College East
    inverse: true

  - year: 2014
    title: break

  - year: Sep 2014
    title: National Junior Robotics Competition The Entrepreneur Award 3rd
    issuer: Science Centre
    inverse: false

  - year: 2014
    title: Edusave Good Progress Award 2014
    issuer: Ministry of Education Singapore
    inverse: true

  - year: 2014
    title: Students That Achieve - Recognition (STAR) Awards 2014
    issuer:  Chua Chu Kang Secondary School
    inverse: false


# Portfolio
portfolio:
  - modal-id: 6
    title: WRO 2018
    subtitle: Robotics Competition
    layout: default
    date: 2019-10-28
    img: roundicons.png
    thumbnail: roundicons-thumbnail.png
    alt: image-alt
    project-date: April 2014
    client: Start Bootstrap
    category: Web Development
    description: Lorem ipsum dolor sit amet, usu cu alterum nominavi lobortis. At duo novum diceret. Tantas apeirian vix et, usu sanctus postulant inciderint ut, populo diceret necessitatibus in vim. Cu eum dicam feugiat noluisse.