url: https://jetong.me
baseurl: 

# Site settings
name: "Jet"
title: Jet Ong
email: s10184291@connect.np.edu.sg
description: "Jet Ong's portfolio"

exclude: [.jekyll-cache, changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives
  - jekyll-time-to-read
  - jekyll-last-modified-at
  - jekyll-multiple-languages-plugin

# Google Analytics
google_analytics: UA-150899950-1

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-1832871158835645"
adsense-data-ad-slot: "1363087678"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: whatsapp
    url: https://wa.me/19793209938
  - title: skype
    url: skype:jetong01?userinfo
  # - title: linkedin
  #   url: https://linkedin.com/in/jet-ong
  - title: github
    url: https://github.com/j370
  - title: bitbucket 
    url: https://bitbucket.org/%7Ba33d1089-188a-431d-9530-3df8cb71e7a4%7D/
  - title: stack-overflow
    url: https://stackoverflow.com/users/6747179/j370
  - title: reddit
    url: https://www.reddit.com/user/j370s
  - title: instagram
    url: https://www.instagram.com/j370s/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

skills:
  - name: Java
    fa: true
    logo: java

  - name: Swift
    fa: true
    logo: swift

  - name: Python
    fa: true
    logo: python

  - name: C++
    fa: false
    logo: cplusplus

  - name: C#
    fa: false
    logo: csharp

  - name: Ruby
    fa: false
    logo: ruby

  - name: HTML
    fa: true
    logo: html5

  - name: CSS
    fa: true
    logo: css3

  - name: JavaScript
    fa: true
    logo: javascript

# Awards
awards:
  - year: 2019
    title: break

  - year: Sep 2019
    title: Championship Award WRO Open 1st
    issuer: Science Center Singapore
    inverse: true

  - year: 2018
    title: break

  - year: Aug 2018
    title: Best Presentation Award WRO Open 3rd
    issuer: Science Center Singapore
    inverse: false

  - year: Aug 2018
    title: Championship Award WRO Open 1st
    issuer: Science Center Singapore
    inverse: true

  - year: 2017
    title: break

  - year: Apr 2017
    title: National Youth Achievement Award Singapore (BRONZE)
    issuer: National Youth Achievement Award Council
    inverse: false

  - year: Mar 2017
    title: IDE Challenge Design Award
    issuer:  NullSpace
    inverse: true

  - year: Feb 2017
    title: ITE College East Robotics Challenge Obstacle Category Merit
    issuer: ITE College East
    inverse: false

  - year: 2016
    title: break

  - year: Jun 2016
    title: National RoboPreneur Carnival Champion
    issuer: Admiralty Secondary School/Nanyang Polytechnic
    inverse: true

  - year: Jul 2016
    title: National RoboPreneur Carnival Best Robot Performance 3rd
    issuer: Admiralty Secondary School/Nanyang Polytechnic
    inverse: false

  - year: Jun 2016
    title: National RoboPreneur Carnival Best Research Journal 1st
    issuer: Admiralty Secondary School/Nanyang Polytechnic
    inverse: true

  - year: 2016
    title: Young Engineer Award (GOLD)
    issuer: Singapore Polytechnic
    inverse: false

  - year: 2015
    title: break

  - year: 2015
    title: ITE College East Robotics Challenge Obstacle Category Merit
    issuer: ITE College East
    inverse: true

  - year: 2014
    title: break

  - year: Sep 2014
    title: National Junior Robotics Competition The Entrepreneur Award 3rd
    issuer: Science Centre
    inverse: false

  - year: 2014
    title: Edusave Good Progress Award 2014
    issuer: Ministry of Education Singapore
    inverse: true

  - year: 2014
    title: Students That Achieve - Recognition (STAR) Awards 2014
    issuer:  Chua Chu Kang Secondary School
    inverse: false


# Portfolio
portfolio:
  - modal-id: 7
    title: Unbiased
    subtitle: Portfolio 2 Assignment
    layout: portfolio/default
    img: unbiased
    project-date: 2019
    tools:  HTML, ASP.NET, Firebase, Python, Artificial Inteligence
    category: Web Application
    description: 7.8/10 bad game reviews are what unbiased is here to fix.
    url: categories#Portfolio-2

  - modal-id: 6
    title: ECycle
    subtitle: Mobile Application Development 1 Assignment
    layout: portfolio/default
    img: EcycleLogo
    project-date: 2019
    tools:  Android Studio, Java
    category: Android Application
    description: The amount of ewaste we waste a year amounts to the entire great wall of China!
    url: categories#Mobile-Application-Development-1

  - modal-id: 5
    title: Guardian 3.0
    subtitle: World Robot Olympiad(WRO) 2019
    layout: portfolio/default
    img: smartcities
    project-date: 2019
    tools:  HTML, ASP.NET, Firebase, Python, Artificial Inteligence, Lego Mindstorms, Tetrix, Raspberry Pi
    category: Robotics
    description: Smart Cities - Guardian 3.0 in Hungary
    url: world robot olympiad (wro)/2019/12/02/wro2019.html

  - modal-id: 4
    title: Service Learning to CDAC @ Redhill and Chong Pang Community Club
    subtitle: Fundamentals for IT Professionals 2 Assignment
    layout: portfolio/default
    img: Service
    project-date: 2019
    tools: Email, Cashless Payment, Social Media
    category: Service Learning
    description: As part of portfolio 2, we went to various Community Clubs to teach various technologies.
    url: fundamentals for it professionals 2/declassified/2019/07/11/fp2a1.html

  - modal-id: 3
    title: Industry Engagement Talks at Google and Alibaba
    subtitle: Fundamentals for IT Professionals 2 Assignment
    layout: portfolio/default
    img: Google
    project-date: August 2018
    tools: Tensorflow, Alibaba Cloud
    category: Service Learning
    description: Learning AI from Google and startup skills from Alibaba.
    url: fundamentals for it professionals 2/declassified/2019/07/18/fp2a2.html

  - modal-id: 2
    title: Guardian 2.0
    subtitle: World Robot Olympiad(WRO) 2018
    layout: portfolio/default
    img: foodmatters
    project-date: August 2018
    tools: HTML, ASP.NET, Firebase, Python, Artificial Inteligence, Lego Mindstorms, Raspberry Pi
    category: Robotics
    description: Food matters - Guardian 2.0 in Thailand
    url: world robot olympiad (wro)/2018/10/05/wro2018.html

  - modal-id: 1
    title: Extreme Control
    subtitle: Portfolio 1 Assignment
    layout: portfolio/default
    img: ExtremeControl
    project-date: 2018
    tools: Android Studio, Java
    category: Android Application
    description: Ever thought that you spend too much time on your mobile devices?
    url: categories#Portfolio-1

# Blog ---------------------------------------
disqus: 'jets-blog'
include: ["_pages"]

# Authors
authors:
  J370:
    name: J370
    display_name: J370
    avatar: 'assets/images/author/jetong.png'
    email: s10184291@connect.np.edu.sg
    web: //jetong.me
    description: "Owner"
  GuoJun:
    web: //guoojunn.wixsite.com/portfolio
  Abi:
    web: //thenosewizard.github.io/P2Blog/
  Jeffrey:
    web: //jeffreypehjt.wixsite.com/portfolio
  Obscar:
    web: //s10185799.wixsite.com/home
  Sabik:

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /blog/page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Language
languages: ["en", "zh-TW"]
exclude_from_localizations: ["javascript", "images", "css", "_i18n", "_sass", "assets", "google957ac7df2ee11022.html"] 